custom:
  bert_base_path: F:/langchain_test_model/LangGraph/gPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large
  cnhuhbert_base_path: F:/langchain_test_model/LangGraph/gPT_SoVITS/pretrained_models/chinese-hubert-base
  device: cpu
  is_half: false
  t2s_weights_path: "F:\\langchain_test_model\\LangGraph\\gPT_SoVITS\\model\\v4\\\u8299\
    \u5B81\u5A1C_ZH\\\u8299\u5B81\u5A1C_ZH-e10.ckpt"
  version: v4
  vits_weights_path: "F:\\langchain_test_model\\LangGraph\\gPT_SoVITS\\model\\v4\\\
    \u8299\u5B81\u5A1C_ZH\\\u8299\u5B81\u5A1C_ZH_e10_s950_l32.pth"
v1:
  bert_base_path: F:/langchain_test_model/LangGraph/gPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large
  cnhuhbert_base_path: GPT_SoVITS/pretrained_models/chinese-hubert-base
  device: cpu
  is_half: false
  t2s_weights_path: GPT_SoVITS/pretrained_models/s1bert25hz-2kh-longer-epoch=68e-step=50232.ckpt
  version: v1
  vits_weights_path: GPT_SoVITS/pretrained_models/s2G488k.pth
v2:
  bert_base_path: F:/langchain_test_model/LangGraph/gPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large
  cnhuhbert_base_path: GPT_SoVITS/pretrained_models/chinese-hubert-base
  device: cpu
  is_half: false
  t2s_weights_path: GPT_SoVITS/pretrained_models/gsv-v2final-pretrained/s1bert25hz-5kh-longer-epoch=12-step=369668.ckpt
  version: v2
  vits_weights_path: GPT_SoVITS/pretrained_models/gsv-v2final-pretrained/s2G2333k.pth
v2Pro:
  bert_base_path: F:/langchain_test_model/LangGraph/gPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large
  cnhuhbert_base_path: GPT_SoVITS/pretrained_models/chinese-hubert-base
  device: cpu
  is_half: false
  t2s_weights_path: GPT_SoVITS/pretrained_models/s1v3.ckpt
  version: v2Pro
  vits_weights_path: GPT_SoVITS/pretrained_models/v2Pro/s2Gv2Pro.pth
v2ProPlus:
  bert_base_path: F:/langchain_test_model/LangGraph/gPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large
  cnhuhbert_base_path: gPT_SoVITS/pretrained_models/chinese-hubert-base
  device: cpu
  is_half: false
  t2s_weights_path: F:\langchain_test_model\LangGraph\gPT_SoVITS\pretrained_models\GPT-SoVITS\s1v3.ckpt
  version: v2ProPlus
  vits_weights_path: F:\langchain_test_model\LangGraph\gPT_SoVITS\pretrained_models\v2Pro\s2Gv2ProPlus.pth
v3:
  bert_base_path: F:/langchain_test_model/LangGraph/gPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large
  cnhuhbert_base_path: GPT_SoVITS/pretrained_models/chinese-hubert-base
  device: cpu
  is_half: false
  t2s_weights_path: GPT_SoVITS/pretrained_models/s1v3.ckpt
  version: v3
  vits_weights_path: GPT_SoVITS/pretrained_models/s2Gv3.pth
v4:
  bert_base_path: F:/langchain_test_model/LangGraph/gPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large
  cnhuhbert_base_path: GPT_SoVITS/pretrained_models/chinese-hubert-base
  device: cpu
  is_half: false
  t2s_weights_path: GPT_SoVITS/pretrained_models/s1v3.ckpt
  version: v4
  vits_weights_path: F:\langchain_test_model\LangGraph\gPT_SoVITS\pretrained_models\gsv-v4-pretrained\s2Gv4.pth
